$ImageName = 'mcr.microsoft.com/businesscentral/sandbox:us'
#$InsiderImageName = 'bcinsider.azurecr.io/bcsandbox:us'
$InsiderImageName = 'bcinsider.azurecr.io/bcsandbox-master:us'
$LicenseFile = '.\BC 15 US.flf'
$ContainerBaseName = 'TigCM'
$DevContainerName = $ContainerBaseName + 'Dev' # should be the same as the ServerName in launch.json for the app
$TestContainerName = $ContainerBaseName + 'Test' # should be the same as the ServerName in launch.json for the test app
$InsiderContainerName = $ContainerBaseName + 'Insider' # should be the same as the ServerName in launch.json for the app
$UserName = 'tigunia' 
$Password = ConvertTo-SecureString 'Navision4ever!' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $Password)
$AppFileName = '.\AppName_1.0.0.1.app'
